### ISSUE TITLE
Misleading error message when passing a Kotlin inline class as a @Prop to a component that also uses @State

### ISSUE THREAD

**Issue by abdyer** [facebook/litho#524] opened 2019-04-02 14:38 UTC
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
```
implementation "com.facebook.litho:litho-core:0.21.0"
implementation "com.facebook.litho:litho-widget:0.21.0"
compileOnly "com.facebook.litho:litho-annotations:0.21.0"
kapt "com.facebook.litho:litho-processor:0.21.0"

implementation "com.facebook.litho:litho-sections-core:0.21.0"
implementation "com.facebook.litho:litho-sections-widget:0.21.0"
compileOnly "com.facebook.litho:litho-sections-annotations:0.21.0"
kapt "com.facebook.litho:litho-sections-processor:0.21.0"
```

## Issues and Steps to Reproduce
1. Pass a Kotlin inline class as a `@Prop` to a Litho component that also implements `@OnCreateInitialState` to set an initial `@State` used in `@OnCreateLayout`.
1. Compile fails with a pair of misleading errors: `Names of parameters of type StateValue must match the name and type of a parameter annotated with @State.` and `Not a valid parameter, should be one of the following: @Prop T somePropName. @TreeProp T someTreePropName. StateValue<T> stateName, where a state param with type T and name stateName is declared elsewhere in the spec. @InjectProp T someInjectPropName.`
1. Changing the Kotlin inline class passed as the `@Prop` to a data class resolves the issue.

## Expected Behavior
Passing an inline class as a `@Prop` should either work as expected or show a more pertinent error message.

## Link to Code
https://gist.github.com/abdyer/d25f368640d7a72d65f466290260a8a0

**Comment by pavlospt** [comment] 2019-04-02 15:07
@abdyer I will take a look at it and see if I can make it work with an inline class as well :) It would help if you also include a whole sample project :)

**Comment by pavlospt** [comment] 2019-04-03 08:51
Update: It seems that this is something caused by KAPT and methods accepting `InlineClass` params. https://github.com/Kotlin/KEEP/issues/104#issuecomment-449782492 Unfortunately there is nothing we can do currently, since the KAPT does not even generate the method and thus Litho processor is unable to extract the delegated method.

**Comment by muraziz** [comment] 2020-04-21 08:54
Closing this as there is not anything actionable here.

**Closed by muraziz** 2020-04-21 08:54 UTC
