### ISSUE TITLE
KeyHandler.java: Found another TextComponent Component with the same key.

### ISSUE THREAD

**Issue by jaceksur** [facebook/litho#360] opened 2018-05-18 20:24 UTC
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
Git pull at 232d09d52f04f8a56812c2aa23e64b34989b7f92

**I've verified that the duplicate key is caused by two threads concurrently trying to build the same instance of a ComponentTree: the main thread and a ComponentLayoutThread.**

The app has a RecyclerView with Litho’s RecyclerBinder. First, N items are loaded. When the user scrolls to the bottom, an RPC to fetch more items is sent. The crash happens when Components are created for the new batch of items, but only if the user tries to scroll vigorously past the end of the list while waiting for the RPC.

The crashing Component is probably the first one that appears in a continuation.

Below are traces of the first and second insertions of the key "1,3,7":

First insertion on main thread:

> dalvik.system.VMStack.getThreadStackTrace(Native Method)
> java.lang.Thread.getStackTrace(Thread.java:580)
> com.facebook.litho.KeyHandler.checkIsDuplicateKey(KeyHandler.java:84)
> com.facebook.litho.KeyHandler.registerKey(KeyHandler.java:65)
> com.facebook.litho.Component.applyStateUpdates(Component.java:530)
> com.facebook.litho.Component.updateInternalChildState(Component.java:438)
> com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:323)
> com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> com.facebook.litho.ComponentLifecycle.resolve(ComponentLifecycle.java:499)
> com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:329)
> com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> com.facebook.litho.LayoutState.createTree(LayoutState.java:1591)
> com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1777)
> com.facebook.litho.LayoutState.calculate(LayoutState.java:1204)
> com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1766)
> com.facebook.litho.ComponentTree.measure(ComponentTree.java:795)
> com.facebook.litho.LithoView.onMeasure(LithoView.java:282)
> android.view.View.measure(View.java:17547)
> android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9034)
> android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1586)
> android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1520)
> android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1334)
> android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1078)
> com.App.common.ui.OverScrollLinearLayoutManager.scrollVerticallyBy(OverScrollLinearLayoutManager.java:64)
> com.App.ui.inline.ScrollToTopLinearLayoutManager.scrollVerticallyBy(ScrollToTopLinearLayoutManager.java:37)
> android.support.v7.widget.RecyclerView.scrollStep(RecyclerView.java:1767)
> android.support.v7.widget.RecyclerView.access$700(RecyclerView.java:157)
> android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4998)
> android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
> android.view.Choreographer.doCallbacks(Choreographer.java:580)
> android.view.Choreographer.doFrame(Choreographer.java:549)
> android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
> android.os.Handler.handleCallback(Handler.java:739)
> android.os.Handler.dispatchMessage(Handler.java:95)
> android.os.Looper.loop(Looper.java:135)
> android.app.ActivityThread.main(ActivityThread.java:5254)
> java.lang.reflect.Method.invoke(Native Method)
> java.lang.reflect.Method.invoke(Method.java:372)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Second insertion on ComponentLayoutThread, which caused the crash:

> dalvik.system.VMStack.getThreadStackTrace(Native Method)
> java.lang.Thread.getStackTrace(Thread.java:580)
> com.facebook.litho.KeyHandler.checkIsDuplicateKey(KeyHandler.java:93)
> com.facebook.litho.KeyHandler.registerKey(KeyHandler.java:65)
> com.facebook.litho.Component.applyStateUpdates(Component.java:530)
> com.facebook.litho.Component.updateInternalChildState(Component.java:438)
> com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:323)
> com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> com.facebook.litho.ComponentLifecycle.resolve(ComponentLifecycle.java:499)
> com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:329)
> com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> com.facebook.litho.LayoutState.createTree(LayoutState.java:1591)
> com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1777)
> com.facebook.litho.LayoutState.calculate(LayoutState.java:1204)
> com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1766)
> com.facebook.litho.ComponentTree.measure(ComponentTree.java:795)
> com.facebook.litho.LithoView.onMeasure(LithoView.java:282)
> android.view.View.measure(View.java:17547)
> android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9034)
> android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1586)
> android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1520)
> android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1334)
> android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1078)
> com.App.common.ui.OverScrollLinearLayoutManager.scrollVerticallyBy(OverScrollLinearLayoutManager.java:64)
> com.App.ui.inline.ScrollToTopLinearLayoutManager.scrollVerticallyBy(ScrollToTopLinearLayoutManager.java:37)
> android.support.v7.widget.RecyclerView.scrollStep(RecyclerView.java:1767)
> android.support.v7.widget.RecyclerView.access$700(RecyclerView.java:157)
> android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4998)
> android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
> android.view.Choreographer.doCallbacks(Choreographer.java:580)
> android.view.Choreographer.doFrame(Choreographer.java:549)
> android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
> android.os.Handler.handleCallback(Handler.java:739)
> android.os.Handler.dispatchMessage(Handler.java:95)
> android.os.Looper.loop(Looper.java:135)
> android.app.ActivityThread.main(ActivityThread.java:5254)
> java.lang.reflect.Method.invoke(Native Method)
> java.lang.reflect.Method.invoke(Method.java:372)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
> 
>

**Comment by passy** [comment] 2018-05-19 08:53
Thanks for the detailed report!

**Comment by jaceksur** [comment] 2018-05-23 20:22
Hi, a short update: I've discovered instances where both keys are inserted from the main thread. I'm starting to think that this might be a case of Litho simultaneously building two ComponentTrees which are erroneously sharing the same KeyHandler.

**Comment by jaceksur** [comment] 2018-05-23 23:30
In any case, here is a log which shows  how it goes wrong. I added logging to KeyHandler.registerKey() - it prints the instance id of the KeyHandler (should be unique per ComponentTree), the calling thread and the key:

> W/KeyHandler(20574): ctor: @3ebd45bb
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3,7
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[main,5,main] 1,3,7!0
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[main,5,main] 1,3,7!0,8
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3,7!0,8
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[main,5,main] 1,3,7!0,8,5
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3,7!0,8,5!0
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[main,5,main] 1,3,7!0,8,5!0,9
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[main,5,main] 1,3,7!0,8,5!0,9,3
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3,7!0,8,5!0,9!0
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3,7!0,8,5!0,9!0,3
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3,7!0,8,5!0,9!0,3,2
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[main,5,main] 1,3,7!0,8,5!0,9!0,3,2

Note that two threads are repeatedly adding a duplicate key, but no exception is thrown because KeyHandler only throws if the component.hasState(). The last two lines pertain to a Component that has state variables, and the exception is thrown:

> E/AndroidRuntime(20574): FATAL EXCEPTION: ComponentLayoutThread1-4
> E/AndroidRuntime(20574): Process: com.google.android.youtube, PID: 20574
> E/AndroidRuntime(20574): java.lang.RuntimeException: Found another ComponentElement Component with the same key.
> E/AndroidRuntime(20574): Found another ComponentElement Component with the same key.
> E/AndroidRuntime(20574): 	at com.facebook.litho.KeyHandler.checkIsDuplicateKey(KeyHandler.java:92)
> E/AndroidRuntime(20574): 	at com.facebook.litho.KeyHandler.registerKey(KeyHandler.java:66)
> E/AndroidRuntime(20574): 	at com.facebook.litho.Component.applyStateUpdates(Component.java:530)
> E/AndroidRuntime(20574): 	at com.facebook.litho.Component.updateInternalChildState(Component.java:438)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:323)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:308)
> E/AndroidRuntime(20574): 	at com.facebook.litho.Layout.create(Layout.java:47)
> E/AndroidRuntime(20574): 	at com.facebook.litho.Layout.create(Layout.java:58)
> E/AndroidRuntime(20574): 	at com.facebook.litho.InternalNode.child(InternalNode.java:719)
> E/AndroidRuntime(20574): 	at com.facebook.litho.Row.resolve(Row.java:114)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:329)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:308)
> E/AndroidRuntime(20574): 	at com.facebook.litho.Wrapper.resolve(Wrapper.java:68)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:329)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentLifecycle.resolve(ComponentLifecycle.java:499)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:329)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentLifecycle.resolve(ComponentLifecycle.java:499)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:329)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
> E/AndroidRuntime(20574): 	at com.facebook.litho.LayoutState.createTree(LayoutState.java:1591)
> E/AndroidRuntime(20574): 	at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1777)
> E/AndroidRuntime(20574): 	at com.facebook.litho.LayoutState.calculate(LayoutState.java:1204)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1766)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentTree.calculateLayout(ComponentTree.java:1442)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentTree.access$2600(ComponentTree.java:69)
> E/AndroidRuntime(20574): 	at com.facebook.litho.ComponentTree$CalculateLayoutRunnable.run(ComponentTree.java:1819)
> E/AndroidRuntime(20574): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> E/AndroidRuntime(20574): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> E/AndroidRuntime(20574): 	at com.facebook.litho.LayoutThreadPoolExecutor$LayoutThreadFactory$1.run(LayoutThreadPoolExecutor.java:73)
> E/AndroidRuntime(20574): 	at java.lang.Thread.run(Thread.java:818)
>

**Comment by mihaelao** [comment] 2018-05-31 09:41
Hey @jaceksur, thanks for the detailed logs, this is really helpful! From the thread names it looks like one of the experimental parallel layout configurations is enabled, can you confirm if the _ComponentLayoutThread1-*_ threads are created by [SplitLayoutResolver](https://github.com/facebook/litho/blob/ea408fea6b735c6a99083af29a623e576584fc15/litho-core/src/main/java/com/facebook/litho/SplitLayoutResolver.java) or [ThreadPoolLayoutHandler](https://github.com/facebook/litho/blob/023a9b7427e26e469482eaaf5d16db2852edce9c/litho-core/src/main/java/com/facebook/litho/ThreadPoolLayoutHandler.java)? If parallel split layout is enabled this might explain this crash, because access to KeyHandler is not synchronized and the background threads would be sharing the same instance as the main thread.

**Comment by vinc3m1** [comment] 2018-05-31 18:00
We aren't using split layouts that I know of (we're making no calls to `setSplitLayoutTag()` or anything else split layout related).

We do definitely use `ComponentsConfiguration.threadPoolForBackgroundThreadsConfig`, does that enable split layout as well?

**Comment by vinc3m1** [comment] 2018-05-31 18:09
I think the interesting part is:

> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[main,5,main] 1,3,7!0,8
> W/KeyHandler(20574): registerKey: @3ebd45bb Thread[ComponentLayoutThread1-4,5,main] 1,3,7!0,8

This means registerKey is being called on the same component updating state on multiple threads, and likely doing duplicate work across those threads, but at the same time. We understand there's some upcoming work to fix that? I just want to confirm that thats the correct assessment here.

**Comment by vinc3m1** [comment] 2018-06-05 03:09
So here's another log I got:
```
06-04 17:56:51.472 1191-2674/com.*.* D/vmi: KeyHandler@1ccf6b registerKey on Component@b391ac8 key: 1 on thread: ComponentLayoutThread1-4 type: WrapperElement
06-04 17:56:51.472 1191-2671/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@88fb4ba key: 1 on thread: ComponentLayoutThread1-1 type: WrapperElement
06-04 17:56:51.474 1191-2672/com.*.* D/vmi: KeyHandler@c298761 registerKey on Component@af46286 key: 1 on thread: ComponentLayoutThread1-2 type: WrapperElement
06-04 17:56:51.479 1191-2674/com.*.* D/vmi: KeyHandler@1ccf6b registerKey on Component@a291b74 key: 1,7 on thread: ComponentLayoutThread1-4 type: ElementsRoot
06-04 17:56:51.479 1191-1191/com.*.* D/vmi: KeyHandler@996389d registerKey on Component@a42112 key: 1 on thread: main type: WrapperElement
06-04 17:56:51.479 1191-2674/com.*.* D/vmi: KeyHandler@1ccf6b registerKey on Component@de1c0e3 key: 1,7,6 on thread: ComponentLayoutThread1-4 type: ElementEvent
06-04 17:56:51.479 1191-2674/com.*.* D/vmi: KeyHandler@1ccf6b registerKey on Component@4767ae0 key: 1,7,6,8 on thread: ComponentLayoutThread1-4 type: Wrapper
06-04 17:56:51.480 1191-2674/com.*.* D/vmi: KeyHandler@1ccf6b registerKey on Component@922c199 key: 1,7,6,8,4 on thread: ComponentLayoutThread1-4 type: Container
06-04 17:56:51.480 1191-1191/com.*.* D/vmi: KeyHandler@996389d registerKey on Component@65883f key: 1,7 on thread: main type: ElementsRoot
06-04 17:56:51.480 1191-2671/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@65883f key: 1,7 on thread: ComponentLayoutThread1-1 type: ElementsRoot
06-04 17:56:51.480 1191-2674/com.*.* D/vmi: KeyHandler@1ccf6b registerKey on Component@a78650c key: 1,7,6,8,4,9 on thread: ComponentLayoutThread1-4 type: Row
06-04 17:56:51.480 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@754de55 key: 1,7,6 on thread: main type: ElementEvent
06-04 17:56:51.480 1191-2671/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@754de55 key: 1,7,6 on thread: ComponentLayoutThread1-1 type: ElementEvent
06-04 17:56:51.480 1191-2674/com.*.* D/vmi: KeyHandler@1ccf6b registerKey on Component@59ec06a key: 1,7,6,8,4,9,2 on thread: ComponentLayoutThread1-4 type: ComponentElement
06-04 17:56:51.481 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@f34695b key: 1,7,6,8 on thread: main type: Wrapper
06-04 17:56:51.481 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@9520ad1 key: 1,7,6,8,4 on thread: main type: Container
06-04 17:56:51.482 1191-2673/com.*.* D/vmi: KeyHandler@5e07936 registerKey on Component@b464037 key: 1 on thread: ComponentLayoutThread1-3 type: WrapperElement
06-04 17:56:51.484 1191-2672/com.*.* D/vmi: KeyHandler@c298761 registerKey on Component@71b830d key: 1,7 on thread: ComponentLayoutThread1-2 type: ElementsRoot
06-04 17:56:51.484 1191-2672/com.*.* D/vmi: KeyHandler@c298761 registerKey on Component@1b2f2c2 key: 1,7,6 on thread: ComponentLayoutThread1-2 type: ElementEvent
06-04 17:56:51.490 1191-2672/com.*.* D/vmi: KeyHandler@c298761 registerKey on Component@334a8d3 key: 1,7,6,8 on thread: ComponentLayoutThread1-2 type: Wrapper
06-04 17:56:51.490 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@d8a4309 key: 1,7,6,8,4,9 on thread: main type: Row
06-04 17:56:51.490 1191-2672/com.*.* D/vmi: KeyHandler@c298761 registerKey on Component@f0e5c10 key: 1,7,6,8,4 on thread: ComponentLayoutThread1-2 type: Container
06-04 17:56:51.490 1191-2672/com.*.* D/vmi: KeyHandler@c298761 registerKey on Component@641790e key: 1,7,6,8,4,9 on thread: ComponentLayoutThread1-2 type: Row
06-04 17:56:51.491 1191-2672/com.*.* D/vmi: KeyHandler@c298761 registerKey on Component@b96ff2f key: 1,7,6,8,4,9,2 on thread: ComponentLayoutThread1-2 type: ComponentElement
06-04 17:56:51.493 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@e65293c key: 1,7,6,8,4,9,2 on thread: main type: ComponentElement
```

If we reduce it only to the suspect threads, main and 1-1, we have:
```
06-04 17:56:51.472 1191-2671/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@88fb4ba key: 1 on thread: ComponentLayoutThread1-1 type: WrapperElement
06-04 17:56:51.479 1191-1191/com.*.* D/vmi: KeyHandler@996389d registerKey on Component@a42112 key: 1 on thread: main type: WrapperElement
06-04 17:56:51.480 1191-1191/com.*.* D/vmi: KeyHandler@996389d registerKey on Component@65883f key: 1,7 on thread: main type: ElementsRoot
06-04 17:56:51.480 1191-2671/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@65883f key: 1,7 on thread: ComponentLayoutThread1-1 type: ElementsRoot
06-04 17:56:51.480 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@754de55 key: 1,7,6 on thread: main type: ElementEvent
06-04 17:56:51.480 1191-2671/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@754de55 key: 1,7,6 on thread: ComponentLayoutThread1-1 type: ElementEvent
06-04 17:56:51.481 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@f34695b key: 1,7,6,8 on thread: main type: Wrapper
06-04 17:56:51.481 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@9520ad1 key: 1,7,6,8,4 on thread: main type: Container
06-04 17:56:51.490 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@d8a4309 key: 1,7,6,8,4,9 on thread: main type: Row
06-04 17:56:51.493 1191-1191/com.*.* D/vmi: KeyHandler@e7ab1e5 registerKey on Component@e65293c key: 1,7,6,8,4,9,2 on thread: main type: ComponentElement
```

Some interesting notes here:
- `KeyHandler` and `Component` instances are **different** at key 1
- `Component` instances become the **same** at key 1,7
  - This is interesting, and I'm not totally sure how this happens but I imagine it's some shared state in ComponentTree between the two threads that isn't threadsafe.
- `KeyHandler` instance **and** `Component` instance become to the **same** at key 1,7,6
  - This makes sense because `KeyHandler` comes from the scoped `ComponentContext`, which would be the same coming from the same component at key 1,7


Finally, I created the stacktrace below by creating a `new Throwable()` with every `registerKey()`, which then I set as the cause of the RuntimeException in `checkIsDuplicateKey()` so we can link the insert with the check, this aligns with @jaceksur's stacktraces from earlier.
```
E/AndroidRuntime: FATAL EXCEPTION: ComponentLayoutThread1-1
                  Process: com.*.*, PID: 1191
                  java.lang.RuntimeException: Found another ElementEvent Component with the same key.
                   KeyHandler@e7ab1e5 registerKey on Component@754de55 key: 1,7,6 on thread: ComponentLayoutThread1-1 type: ElementEvent
                  Found another ElementEvent Component with the same key.
                   KeyHandler@e7ab1e5 registerKey on Component@754de55 key: 1,7,6 on thread: ComponentLayoutThread1-1 type: ElementEvent
                      at com.facebook.litho.KeyHandler.checkIsDuplicateKey(KeyHandler.java:97)
                      at com.facebook.litho.KeyHandler.registerKey(KeyHandler.java:68)
                      at com.facebook.litho.Component.applyStateUpdates(Component.java:530)
                      at com.facebook.litho.Component.updateInternalChildState(Component.java:438)
                      at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:322)
                      at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
                      at com.facebook.litho.ComponentLifecycle.resolve(ComponentLifecycle.java:482)
                      at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:328)
                      at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
                      at com.facebook.litho.LayoutState.createTree(LayoutState.java:1594)
                      at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1780)
                      at com.facebook.litho.LayoutState.calculate(LayoutState.java:1205)
                      at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1833)
                      at com.facebook.litho.ComponentTree.calculateLayout(ComponentTree.java:1504)
                      at com.facebook.litho.ComponentTree.access$2700(ComponentTree.java:71)
                      at com.facebook.litho.ComponentTree$CalculateLayoutRunnable.run(ComponentTree.java:1886)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at com.facebook.litho.LayoutThreadPoolExecutor$LayoutThreadFactory$1.run(LayoutThreadPoolExecutor.java:73)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.Throwable
                      at com.facebook.litho.KeyHandler.registerKey(KeyHandler.java:69)
                      at com.facebook.litho.Component.applyStateUpdates(Component.java:530)
                      at com.facebook.litho.Component.updateInternalChildState(Component.java:438)
                      at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:322)
                      at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
                      at com.facebook.litho.ComponentLifecycle.resolve(ComponentLifecycle.java:482)
                      at com.facebook.litho.ComponentContext.resolveLayout(ComponentContext.java:328)
                      at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:303)
                      at com.facebook.litho.LayoutState.createTree(LayoutState.java:1594)
                      at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1780)
                      at com.facebook.litho.LayoutState.calculate(LayoutState.java:1205)
                      at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1833)
                      at com.facebook.litho.ComponentTree.measure(ComponentTree.java:853)
                      at com.facebook.litho.LithoView.onMeasure(LithoView.java:305)
                      at android.view.View.measure(View.java:18794)
                      at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9064)
                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1583)
                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
                      at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1331)
                      at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1075)

```

This can be fairly consistently reproduced by loading a list continuation and scrolling down immediately as it loads. The race presumably happens when the main thread adapter requests `measure()` while we've already scheduled and started running `mCurrentCalculateLayoutRunnable`

So, my conclusions so far are that the `calculateLayout()` and `measure()` functions both call through to `calculateLayoutState()` at the same time. They synchronize on `this` (the ComponentTree) before and after the call to `calculateLayoutState()` but **not during**. This means they could both see that the layout is not valid in the first synchronized block, then both start `calculateLayoutState()` at the same time.

While `calculateLayoutState()` does use `mRoot.makeShallowCopy()` to operate on different component roots, that copy is probably not deep enough to separate the states of all the children down the full layout tree. This results in the 2 threads mutating the same Component after the first child, then the same Component Context, then using the same KeyHandler and eventually crashing.

Now, the question is how to fix it. Tomorrow I'm planning to look into a way to:
1. Have the main thread to wait for background calculation if it already started
2. Have the background thread return early if the main thread has already started

Now, I also saw that there is an `mLayoutLock` that has a pretty scary sounding warning:
> Specify a lock to be acquired during layout. This is an advanced feature that can lead to deadlock if you don't know what you are doing.
Also, the lock only prevents calculateLayoutState from happening at the same time on multiple threads, but doesn't seem to gate the checks that let them return early if another thread is already calculating. Am I correct in that interpretation of the code?

Either way, I would love to know if there are any issues with my planned approach or if using a `new Object()` (or the `ComponentTree` itself?) for `mLayoutLock` may simply solve our problem. However, we do also want to prevent duplicate calculation for performance reasons, so I don't think it will be adequate to simply stop the crash and still calculate layout twice with more thread contention due to increased locking.

**Comment by mihaelao** [comment] 2018-06-05 10:52
@vinc3m1 is the component that shares the key handler on different threads passed down as a prop? talking to @pasqualeanatriello we might know what's causing this if that's the case, just wanted to be sure before we send a fix.

**Comment by vinc3m1** [comment] 2018-06-05 15:45
Ah yes this may be happening since we dynamically create our trees. We are using a `@Prop List<Component> children` on our containers, so that might be it.

**Comment by vinc3m1** [comment] 2018-06-05 15:59
Actually another important point is that we also use 
`@Prop RunnableFuture<Component> componentFuture`
`@Prop Observable<Component> delegateSource`
`@Prop Component child`

The `Future` and `Observable` versions will update `StateValues`, either through `StateValue<Component>.set()` inside `onCreateInitialState`, or through the static `@OnUpdateState` function when outside of `onCreateInitialState`.

**Comment by mihaelao** [comment] 2018-06-05 16:32
This sounds like a legitimate synchronization bug when the same component instance is accessed on different threads. This is fine for the simple case when the component is passed as prop, because a copy is created before creating its layout, but we don't do the same when the component is wrapped in another data structure and passed as prop. I'll working on a fix right now. Thanks for the thoughtful analysis!

**Comment by mihaelao** [comment] 2018-06-11 16:21
Hey @vinc3m1, 9cf19ac fixes the issue I described above. Please let me know if this still doesn't resolve the bug you described

**Comment by mihaelao** [comment] 2018-06-13 09:45
Closing this, @vinc3m1 please reopen if this is still not fixed

**Closed by mihaelao** 2018-06-13 09:45 UTC
