### ISSUE TITLE
EventTrigger usage problem

### ISSUE THREAD

**Issue by didixyy** [facebook/litho#619] opened 2019-12-17 11:05 UTC
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.29.0
    implementation "com.facebook.litho:litho-core:0.29.0"
    implementation "com.facebook.litho:litho-widget:0.29.0"
    implementation "com.facebook.litho:litho-annotations:0.29.0"
    annotationProcessor "com.facebook.litho:litho-processor:0.29.0"
    // SoLoader
    implementation 'com.facebook.soloader:soloader:0.5.1'
    // For integration with Fresco
    implementation("com.facebook.litho:litho-fresco:0.29.0}") {
        exclude group: 'com.facebook.fresco'
    }
## Issues and Steps to Reproduce
i hava a child componemt ASpec ,it register a tigger annotation ,when i use in ColumnSpec it can use ,but when i use in HorizontalScrollSpec it can not work.

## Expected Behavior
i want trigger can work in HorizontalScrollSpec child

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using return Column.create(c)
.child(HorizontalScroll.create(c)
    .widthPercent(100)
    .aspectRatio(1.78f)
    .contentProps(MyComponent.create(c)
        .widthPercent(100)
        .key("click_outside_key" + bean.hashCode())
      .build();

**Comment by topwu** [comment] 2019-12-20 14:51
I think the root cause is that Trigger isn't available between different ComponentTrees, and HorizontalScrollSpec creates another ComponentTree for the child component. Could you share more context what you want to achieve?

**Comment by adityasharat** [comment] 2020-01-01 15:36
As @topwu suggested, could you please share some details about what you want to achieve? Maybe there is some other way to do it.

**Comment by colriot** [comment] 2020-01-20 17:20
Hi @didixyy. Can you please add the sample code (can be a small sample project, or you can modify our `PlaygroundComponentSpec.java` with your repro code and share it here) to reproduce the issue?

**Comment by adityasharat** [comment] 2020-03-03 16:37
Closing this! Please reopen if required

**Closed by adityasharat** 2020-03-03 16:37 UTC
