### ISSUE TITLE
ProgressSpec exception

### ISSUE THREAD

**Issue by marwanf1** [facebook/litho#207] opened 2017-07-02 06:46 UTC
Whenever I want to add a Progress component to my views an exception is being thrown.

Drawable android:drawable/progress_medium_material has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).

The way I'm creating the Progress is as follows: Progress.create(c).colorRes(R.color.colorAccent)

Am I missing something or is this a bug?

**Comment by passy** [comment] 2017-07-12 12:03
Hey, sorry for the delay.

I've tried to reproduce this, but `colorRes` in `Progress` works fine for me. This seems to be related to a project setup issue you have.

Are you still seeing this issue? Could you post a minimal example of how to reproduce this?

**Comment by passy** [comment] 2017-07-17 15:25
Closing this in lieu of a repro case. If you are still seeing this, please let me know!

**Closed by passy** 2017-07-17 15:25 UTC
