### ISSUE TITLE
Occasionally UI jumps to the new content position after setComponentAsync twice with StaggeredGridRecyclerConfiguration

### ISSUE THREAD

**Issue by ar-g** [facebook/litho#316] opened 2018-02-19 07:20 UTC
Our use case is to show part of the content, load and show full content.  But sometimes after second set UI jumps to the place where new content inserted.
```kotlin
//called twice
        lithoView.setComponentAsync(// setComponent produce the same result
                AdPageList.create(sectionContext)
                        .model(data)
                        .build()
        )

@LayoutSpec
object AdPageListSpec {
    @OnCreateLayout
    fun onCreateLayout(c: ComponentContext): Component {
        return RecyclerCollectionComponent.create(c)
                .backgroundRes(R.color.white)
                .disablePTR(true)
                .recyclerConfiguration(
                        StaggeredGridRecyclerConfiguration<SectionBinderTarget>(App.getInstance().feedSpans)
                )
                .section(
                        AdPage.create(SectionContext(c))
                                .model(model)
                                .build()
                )
                .build()
    }
}

```
The AdPage is a mixed bag of Components with .isFullSpan(true)
and ViewRenderInfos. It seems to work fine without StaggeredGridRecyclerConfiguration, I also noticed that if I cache model for some components UI won't jump too.

**Comment by mihaelao** [comment] 2019-06-20 10:23
Difficult to say what's happening here without knowing the implementation of AdPage section; this could be something caused by diffing not working properly because the comparison methods are not working if you're using a DataDiffSection. Closing, @ar-g if you are still having trouble please create another issue with the code for the section and we'll take another look

**Closed by mihaelao** 2019-06-20 10:23 UTC
