### ISSUE TITLE
UI update time increased when updating from 0.23.0 to 0.24.0

### ISSUE THREAD

**Issue by TimurKhairnasov** [facebook/litho#631] opened 2020-02-19 04:59 UTC
- I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.24.0

## Issues and Steps to Reproduce
When i updated version from 0.23.0 to 0.24.0 UI updated time ( litho_view.setComponent() ) increased. Especially this behavior you can see on week devices.

Activity:
`
litho_view.setComponentAsync(RecyclerCollectionComponent.create(c)
				.disablePTR(true)
				.section(MediaPickerSection.create(SectionContext(c))
						.store(store)
						.build())
				.build()
		)
`

Sections:
`
@GroupSectionSpec
object MediaPickerSectionSpec {

	@OnCreateChildren
	fun onCreateLayout(
			c: SectionContext,
			@Prop store: MediaPickerStore
	): Children {
		return children(c) {

			val mediaMap = store.mediaMap.chunked(3).withIndex()
			for ((index, medias) in mediaMap) {
				singleComponentSection(c) {
					key(index.toString())

					sectionComponent {
						row(c) {
							medias.forEach { media ->
								child(ImagePickerItem.create(c)
										.image(media)
										.heightPx(400)
										.widthPx(400))
							}
						}
					}
				}
			}
		}.build()
	}
}
`
Component:
`
@LayoutSpec
object ImagePickerItemSpec {

	@OnCreateLayout
	fun onCreateLayout(c: ComponentContext,
					   @Prop image: MediaPickerStore.Media
	): Component {
		return row(c) {

			frescoImage(c) {
				controller(Fresco.newDraweeControllerBuilder()
						.setImageRequest(ImageRequestBuilder
								.newBuilderWithSource("file:///${image.mediaPath}".toUri())
								.build())
						.build())
			}
		}.build()
	}
}
`

**Comment by muraziz** [comment] 2020-02-19 11:15
Hey @TimurKhairnasov, 

Can you try sync version of `setComponent`, i.e. instead of 
> litho_view.setComponentAsync(RecyclerCollectionComponent.create(c) 

use `litho_view.setComponent(RecyclerCollectionComponent.....)`?

Async update will post runnable to BG thread and you can trigger update earlier by using 'sync' version.

Also you can use systrace to see where the delay is coming from.

Also, the sequence should be like this: OnCreateChildren of groupsection is called to get all the dataset, then OnCreateLayout of ImagePickerItemSpec should be called for at least items on screen and then for items beyond the screen.

**Comment by TimurKhairnasov** [comment] 2020-02-20 12:52
I've tried use setComponent. Result is the same, only with freeze.

I'am talking about update existed list. It should update only one of sections.

I've used profiler to get the difference between versions. Here's results:
![android  ~:AndroidStudioProjects:android  - AndroidStudioProjects-android-app 2020-02-20 09-55-55](https://user-images.githubusercontent.com/45445109/74934957-25923880-5409-11ea-86fb-bfae61eef531.png)

![android  ~:AndroidStudioProjects:android  -  :app:src:main:java:com:blogteam:android:ui:main:reactionlist:ReactionListActivit… 2020-02-20 09-41-29](https://user-images.githubusercontent.com/45445109/74934967-29be5600-5409-11ea-8361-7d140d644d13.png)

Here you can see, that some processes lasts longer in latest version.

It's look like only difference in GC, but other processes are the same.

**Comment by muraziz** [comment] 2020-02-20 14:27
@TimurKhairnasov I'm not sure GC is the cause here. It seems like something is waiting on certain UI to be ready. 

Do you think you can add your patch to our sample app (under 'sample' folder) and repro it? If that is possible, then we could try to repro it in our side and figure out what is the culprit.

**Comment by muraziz** [comment] 2020-04-21 08:55
Closing this issue, as it's likely has been fixed in new versions.

**Closed by muraziz** 2020-04-21 08:55 UTC
